### ISSUE TITLE
Bug report: Exception occurs when the same object are attached to header

### ISSUE THREAD

**Issue by konifar** [recruit-mp/android-HeaderFooterGridView#15]
I'll write detail later.

``` java
java.lang.ClassCastException: android.widget.AbsListView$LayoutParams cannot be cast to android.view.ViewGroup$MarginLayoutParams
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5817)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
       at jp.co.recruit_mp.android.widget.HeaderFooterGridView$FullWidthFixedViewLayout.onMeasure(HeaderFooterGridView.java:301)
       at android.view.View.measure(View.java:18573)
       at android.widget.GridView.onMeasure(GridView.java:1078)
       at jp.co.recruit_mp.android.widget.HeaderFooterGridView.onMeasure(HeaderFooterGridView.java:98)
       at android.view.View.measure(View.java:18573)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
       at android.view.View.measure(View.java:18573)
```

**Comment by konifar** [comment]
I understood the cause of this. If we use same header object in ListView and HeaderFooterGridView, this error occurred.

``` java
customViewWithListView.addHeader(header);
customViewWithGridView.addHeader(header); // header is same object.
```

**Comment by yhirano** [comment]
Thanks for report.

The part of exception is derived from the original code by Google. (see [HeaderGridView.java](http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android-apps/4.4_r1/com/android/photos/views/HeaderGridView.java))
If you want to attach the same object to header, recommend that create a new instance.

**Comment by konifar** [comment]
Thanks! I know. I create new instance 😉

**Comment by konifar** [comment]
So I close this issue. Thanks for support!
